### ISSUE TITLE
Отличный вирус

### ISSUE THREAD

**Issue by SizRex** [FlowseaI/zapret-discord-youtube#1]
Спасибо, работает.

- Спасибо 💖

**Comment by SizRex** [comment]
![image](https://github.com/user-attachments/assets/b8bf2c8a-8eba-4bcb-8ff7-a5d554e0d875)

**Comment by FlowseaI** [comment]
Прошу не отправлять такие картинки.

**Comment by SizRex** [comment]
Virus, he edited my comment.
Вирус, он изменил мой коммент!
